import OpenAI from "openai"
import { TwitterApi } from "twitter-api-v2"
import { Redis } from "@upstash/redis"

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
})

const twitterClient = new TwitterApi({
  appKey: process.env.X_API_KEY,
  appSecret: process.env.X_API_SECRET,
  accessToken: process.env.X_ACCESS_TOKEN,
  accessSecret: process.env.X_ACCESS_SECRET,
})

const rwClient = twitterClient.readWrite

const redisUrl =
  process.env.KV_REST_API_URL ||
  process.env.UPSTASH_REDIS_REST_URL ||
  process.env.UPSTASH_REDIS_REST_KV_REST_API_URL

const redisToken =
  process.env.KV_REST_API_TOKEN ||
  process.env.UPSTASH_REDIS_REST_TOKEN ||
  process.env.UPSTASH_REDIS_REST_KV_REST_API_TOKEN

const redis = new Redis({
  url: redisUrl,
  token: redisToken,
})

async function fetchJson(url) {
  const response = await fetch(url, {
    headers: {
      Accept: "application/json",
      "User-Agent": "MemeMachineAutomata/1.0",
    },
  })

  if (!response.ok) {
    throw new Error(`Fetch failed: ${url} - ${response.status}`)
  }

  return response.json()
}

function cleanSymbol(symbol) {
  if (!symbol) return ""

  return String(symbol)
    .replace(/[^a-zA-Z0-9]/g, "")
    .slice(0, 12)
    .toUpperCase()
}

function cleanName(name) {
  if (!name) return ""

  return String(name)
    .replace(/[^\w\s.$-]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 40)
}

function isBadTopicText(text) {
  if (!text) return true

  const lower = text.toLowerCase()

  const badPhrases = [
    "http",
    "www.",
    "t.co",
    "airdrop",
    "giveaway",
    "claim",
    "reward",
    "click",
    "join",
    "telegram",
    "discord",
    "wallet",
    "connect wallet",
    "presale",
    "whitelist",
    "guaranteed",
    "100x",
    "biggest",
    "signal",
    "pump signal",
  ]

  return badPhrases.some((phrase) => lower.includes(phrase))
}

function isCleanCandidate(candidate) {
  const symbol = candidate.symbol || ""
  const name = candidate.name || ""
  const description = candidate.description || ""

  // Skip if all useful fields are empty.
  if (!symbol && !name) return false

  // Skip obvious spam/scam text.
  if (isBadTopicText(symbol) || isBadTopicText(name) || isBadTopicText(description)) {
    return false
  }

  // Prefer short symbols.
  if (symbol && symbol.length >= 2 && symbol.length <= 12) {
    return true
  }

  // Allow short clean names.
  if (name && name.length >= 2 && name.length <= 24) {
    return true
  }

  return false
}

async function getTrendCandidates() {
  const candidates = []

  // DEX Screener: top boosted tokens
  try {
    const boosted = await fetchJson(
      "https://api.dexscreener.com/token-boosts/top/v1"
    )

    if (Array.isArray(boosted)) {
      for (const item of boosted.slice(0, 20)) {
        const chain = item.chainId || ""
        const tokenAddress = item.tokenAddress || ""
        const description = item.description || ""

        const rawSymbol =
          item.symbol ||
          item.baseToken?.symbol ||
          item.tokenSymbol ||
          ""

        const rawName =
          item.name ||
          item.baseToken?.name ||
          item.tokenName ||
          ""

        const cleanedSymbol = cleanSymbol(rawSymbol)
        const cleanedName = cleanName(rawName)
        const cleanedDescription = cleanName(description)

        const candidate = {
          source: "dexscreener_boosted",
          id: `dex:${chain}:${tokenAddress || cleanedSymbol || cleanedName}`,
          chain,
          symbol: cleanedSymbol,
          name: cleanedName,
          description: cleanedDescription,
        }

        if (isCleanCandidate(candidate)) {
          candidates.push(candidate)
        }
      }
    }
  } catch (error) {
    console.error("DEX Screener trend fetch failed:", error.message)
  }

  // CoinGecko: trending search coins
  try {
    const cg = await fetchJson("https://api.coingecko.com/api/v3/search/trending")

    const coins = cg?.coins || []

    for (const wrapped of coins.slice(0, 15)) {
      const item = wrapped?.item || {}

      const candidate = {
        source: "coingecko_trending",
        id: `cg:${item.id || item.coin_id || item.symbol || item.name}`,
        chain: "",
        symbol: cleanSymbol(item.symbol),
        name: cleanName(item.name),
        description: "",
      }

      if (isCleanCandidate(candidate)) {
        candidates.push(candidate)
      }
    }
  } catch (error) {
    console.error("CoinGecko trend fetch failed:", error.message)
  }

  return candidates
}

function makeCaption(topic) {
  const label = topic.symbol ? `$${topic.symbol}` : topic.name

  const captions = [
    `M.M.A. trend scan detected ${label} energy 🤖\n\nMachine-made meme. No financial advice.`,
    `The machine found fresh meme smoke around ${label}.\n\nGenerated by Meme Machine Automata 🤖 No financial advice.`,
    `Trend radar picked up ${label}.\n\nM.M.A. made this visual transmission. No financial advice.`,
    `Automated meme output based on today’s trend noise: ${label} 🤖\n\nNo financial advice.`,
  ]

  return captions[Math.floor(Math.random() * captions.length)].slice(0, 260)
}

function makeImagePrompt(topic) {
  const label = topic.symbol ? `$${topic.symbol}` : topic.name

  const sourceText =
    topic.source === "dexscreener_boosted"
      ? "a boosted memecoin trend"
      : "a trending crypto search topic"

  return `
Create an original funny AI-generated meme image inspired by ${sourceText}.

Trend topic:
${label}

Theme:
A chaotic autonomous meme machine notices a trending memecoin signal and creates a funny crypto-degen scene.

Visual direction:
- retro computer / AI meme machine energy
- funny crypto trader or robot mascot
- exaggerated cartoon expression
- memecoin chaos
- green candles, red candles, heavy bags, terminal screen, or degen dashboard
- original scene, not a copy of an existing meme template
- no real celebrity likeness
- no readable brand logos
- no financial promises
- no "buy now"
- no "100x"
- no guaranteed profit
- internet meme style
- bold, funny, high contrast composition
`
}

export default async function handler(req, res) {
  if (req.method !== "GET") {
    return res.status(405).json({ error: "Use GET instead." })
  }

  let stage = "start"

  try {
    const secret = req.query.secret

    if (!secret || secret !== process.env.BOT_SECRET) {
      return res.status(401).json({ error: "Unauthorized." })
    }

    if (!redisUrl || !redisToken) {
      return res.status(500).json({
        error: "Missing Redis environment variables.",
      })
    }

    // Use this to test without posting:
    // /api/x-trend?secret=YOUR_SECRET&dryRun=true
    const dryRun = req.query.dryRun === "true"

    stage = "rate_limit"

    const today = new Date().toISOString().slice(0, 10)
    const dailyKey = `mma:trend-post-count:${today}`

    const currentCount = Number((await redis.get(dailyKey)) || 0)

    // Keep this low while testing.
    if (currentCount >= 3 && !dryRun) {
      return res.status(200).json({
        status: "ok",
        skipped: "Daily trend post limit reached.",
        currentCount,
      })
    }

    stage = "get_trends"

    const candidates = await getTrendCandidates()

    if (!candidates.length) {
      return res.status(200).json({
        status: "ok",
        skipped: "No clean trend candidates found.",
      })
    }

    let selected = null

    for (const candidate of candidates) {
      const postedKey = `mma:trend-posted:${candidate.id}`
      const alreadyPosted = await redis.get(postedKey)

      if (!alreadyPosted) {
        selected = candidate
        break
      }
    }

    if (!selected) {
      return res.status(200).json({
        status: "ok",
        skipped: "All recent clean trend candidates were already used.",
        checked: candidates.slice(0, 8),
      })
    }

    const caption = makeCaption(selected)
    const finalPrompt = makeImagePrompt(selected)

    if (dryRun) {
      return res.status(200).json({
        status: "ok",
        dryRun: true,
        selected,
        caption,
        imagePrompt: finalPrompt,
        allCandidates: candidates.slice(0, 10),
      })
    }

    stage = "generate_image"

    const imageResult = await openai.images.generate({
      model: process.env.OPENAI_IMAGE_MODEL || "gpt-image-1-mini",
      prompt: finalPrompt,
      size: "1024x1024",
      quality: "low",
    })

    const imageBase64 = imageResult.data?.[0]?.b64_json

    if (!imageBase64) {
      return res.status(500).json({
        error: "No image returned from OpenAI.",
      })
    }

    stage = "upload_media"

    const imageBuffer = Buffer.from(imageBase64, "base64")

    const mediaId = await rwClient.v1.uploadMedia(imageBuffer, {
      mimeType: "image/png",
    })

    stage = "post_trend"

    const posted = await rwClient.v2.tweet({
      text: caption,
      media: {
        media_ids: [mediaId],
      },
    })

    stage = "mark_posted"

    await redis.set(`mma:trend-posted:${selected.id}`, "posted", {
      ex: 60 * 60 * 24 * 14,
    })

    await redis.incr(dailyKey)
    await redis.expire(dailyKey, 60 * 60 * 36)

    return res.status(200).json({
      status: "ok",
      trendMode: true,
      selected,
      caption,
      postedTweetId: posted?.data?.id || null,
    })
  } catch (error) {
    console.error("X trend bot failed:", {
      stage,
      message: error?.message,
      code: error?.code,
      data: error?.data,
    })

    return res.status(500).json({
      error: "X trend bot failed.",
      stage,
      details: error?.message || "Unknown error",
      code: error?.code || null,
      data: error?.data || null,
    })
  }
}
